export const CENSUS_QUESTIONS = [
  {
    id: 1,
    type: 'text' as const,
    prompt: 'Full name of the resident:',
    response: '',
  },
  {
    id: 2,
    type: 'number' as const,
    prompt: 'Age of the resident:',
    response: null,
  },
  {
    id: 3,
    type: 'option' as const,
    prompt: 'Gender:',
    options: ['Male', 'Female', 'Non-binary', 'Prefer not to say'],
    response: '',
  },
  {
    id: 4,
    type: 'option' as const,
    prompt: 'Highest level of education attained:',
    options: [
      'No formal education',
      'Elementary',
      'Secondary',
      'Technical/Vocational',
      'Undergraduate',
      'Graduate',
    ],
    response: '',
  },
  {
    id: 5,
    type: 'text' as const,
    prompt: 'Current occupation:',
    response: '',
  },
  {
    id: 6,
    type: 'option' as const,
    prompt: 'Do you have any disabilities?',
    options: ['Yes', 'No'],
    response: '',
    other: '',
  },
  {
    id: 7,
    type: 'option' as const,
    prompt: 'Marital status:',
    options: [
      'Single',
      'Married',
      'Domestic partnership',
      'Divorced',
      'Widowed',
    ],
    response: '',
  },
  {
    id: 8,
    type: 'option' as const,
    prompt: 'Monthly income range:',
    options: [
      'Less than $1,000',
      '$1,000 to $2,000',
      '$2,001 to $5,000',
      'More than $5,000',
    ],
    response: '',
  },
  {
    id: 9,
    type: 'option' as const,
    prompt: 'Do you have health insurance?',
    options: ['Yes', 'No'],
    response: '',
  },
  {
    id: 10,
    type: 'option' as const,
    prompt: 'Number of people in the household:',
    options: ['1', '2-3', '4-5', '6 or more'],
    response: '',
  },
  {
    id: 11,
    type: 'option' as const,
    prompt: 'Type of housing:',
    options: ['House', 'Apartment', 'Room', 'Other'],
    response: '',
    other: '',
  },
  {
    id: 12,
    type: 'option' as const,
    prompt: 'What type of internet connection do you have at home?',
    options: ['Fiber optic', 'DSL', 'Cable', 'Satellite', 'None'],
    response: '',
  },
];
